CREATE TABLE "ORGANIZER" 
(
  "NAZWISKO"  VARCHAR(30),
  "IMIE"  VARCHAR(30),
  "FIRMA"  VARCHAR(50),
  "EMAIL"  VARCHAR(50),
  "ADRES"  VARCHAR(50),
  "KOD"  NUMERIC(5,0),
  "MIASTO" INTEGER,
  "TEL" VARCHAR(30),
  "FAX" VARCHAR(30),
  "KOM" VARCHAR(30),
  "INFORMACJE" VARCHAR(255),
  "GRUPA" INTEGER,

 FOREIGN KEY (MIASTO) REFERENCES MIASTO (INDEKS),
 FOREIGN KEY (GRUPA) REFERENCES GRUPA (INDEKS)

);
